# Generated by Django 4.1.7 on 2023-03-21 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_office', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='TypeAppointment',
            fields=[
                ('type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de cita medica',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('is_done', models.BooleanField(default=False)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.typeappointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patient')),
            ],
            options={
                'verbose_name': 'Cita medica',
            },
        ),
    ]
